### ISSUE TITLE
サイト背景

### ISSUE THREAD

**Issue by ysakasin** [inct-www-club/BlogGem#4]
サイトの背景をどうするか。
そもそも使うのか、白のままにするのか。

**Comment by MOGLAS999** [comment]
白でも悪くないんですけどちょっと寂しい気がします。
自作は厳しそうなんで、色を付けるかフリー素材を使うのはどうでしょう。

**Comment by ysakasin** [comment]
natural_paper.pngが、なかなか良いですね！！
cssのbackground-attachmentは、個人的にscrollの方が好きですがどうでしょう？

**Comment by MOGLAS999** [comment]
自分もscrollいいと思います。
ちなみに背景はhttp://subtlepatterns.com/ から借りました。

**Comment by ysakasin** [comment]
ちょっと調べたところ、この素材はクリエイティブ・コモンズ・ライセンスの下で配布されていて、原作者の表記が義務付けられています。正直、面倒な感じを受けます。
もし、似たような素材で、ライセンス的に問題なさそうなものがあれば、そちらにした方が良いかもしれませんね。

**Comment by MOGLAS999** [comment]
違うサイトから別の素材を見つけてきたのでコミットしておきました。
ご確認下さい。

**Comment by ysakasin** [comment]
やっぱり、natural_paper.pngの良さが目立ってますね。
もともとあるリンク一覧に、使用素材として表示するのもアリだと思うので、ライセンスのことは、あまり気にしなくてもいいかも……

いまのところ、私はnatural_paper.png押しです。

**Comment by MOGLAS999** [comment]
ではリンク集に載せてnatural_paper.pngを使用する方向でいきますか。
リンク集作ります。
